In [ ]:
import pandas as pd
prod=pd.Series([30,40,50,60])
print(prod)

0    30
1    40
2    50
3    60
dtype: int64

In [ ]:
import pandas as pd
production=pd.Series (
    [30,60,45,25],
          index=["wheat","rice","maize","barley"]
)
print(production)

wheat     30
rice      60
maize     45
barley    25
dtype: int64

In [ ]:
#by crop name (label)
print(production["rice"])
print(production.loc["rice"])    #loc=loaction by label

60
60

In [ ]:
#by positioning
print(production.iloc[0]) #iloc=indexing by location

30

In [ ]:
print(production.sum())
print(production.max())
print(production.mean())
print(production.idxmax()) #maximum production crop, it prints the index label of the maximum value in the Series
print(production.idxmax(),"is having max value of",production.max())

160
60
40.0
rice
rice is having max value of 60

In [ ]:
# increase all crop production by10%(good harvest year)
increased_production=production*1.10
print(increased_production)

wheat     33.0
rice      66.0
maize     49.5
barley    27.5
dtype: float64

In [ ]:
#crop production greater than 40 tons
high_production=production[production>40]
print(high_production)
print()
print(production>40)

rice     60
maize    45
dtype: int64

wheat     False
rice       True
maize      True
barley    False
dtype: bool

In [ ]:
#.loc -label-based indexing -you use row/coloumn labels(names)
#rules
#use index labels, not positions
#

In [ ]:
import pandas as pd
df=pd.DataFrame({
    "name":["akhil","bobby","charan"],
    "age":[25,30,35],
    "city":["ny","la","chicago"]
},index=["a","b","c"])
print(df)
print()
print(df.loc["b"])

     name  age     city
a   akhil   25       ny
b   bobby   30       la
c  charan   35  chicago

name    bobby
age        30
city       la
Name: b, dtype: object

In [ ]:
print(df)
print()
print(df.loc[["a","c"],["name","city"]])

     name  age     city
a   akhil   25       ny
b   bobby   30       la
c  charan   35  chicago

     name     city
a   akhil       ny
c  charan  chicago

In [ ]:
print(df.loc["a":"c"]) #includes

     name  age     city
a   akhil   25       ny
b   bobby   30       la
c  charan   35  chicago

In [ ]:
import pandas as pd
df=pd.DataFrame({
    "name":["akhil","bobby","charan"],
    "age":[25,30,35],
    "city":["ny","la","chicago"]
},index=["a","b","c"])

print(df.loc[df["age"]>28,["name","age"]])

     name  age
b   bobby   30
c  charan   35

In [ ]:
print(df.iloc[[0,1]])

    name  age city
a  akhil   25   ny
b  bobby   30   la

In [ ]:
print(df.iloc[[0,1],[1,2]]) #selects rows and coloumns by position

   age city
a   25   ny
b   30   la

In [ ]:
print(df.iloc[0:1])

    name  age city
a  akhil   25   ny

In [ ]:
#a dataFrame is two -dimensional data structure.A table like an excel sheet-made of multiple series

In [ ]:
import pandas as pd
data={
    "farm":["farmA","farmB","farmC","farmD"],
    "crop":["wheat","rice","wheat","maize"],
    "area_hectares":[10,15,8,12],
    "production_tons":[30,60,24,36]
}
df=pd.DataFrame(data)
print(df)

    farm   crop  area_hectares  production_tons
0  farmA  wheat             10               30
1  farmB   rice             15               60
2  farmC  wheat              8               24
3  farmD  maize             12               36

In [ ]:
df.head(2) #for first few rows

    farm   crop  area_hectares  production_tons
0  farmA  wheat             10               30
1  farmB   rice             15               60

In [ ]:
df.tail(3) #for bottom few rows

    farm   crop  area_hectares  production_tons
1  farmB   rice             15               60
2  farmC  wheat              8               24
3  farmD  maize             12               36

In [ ]:
df.info()   #basic information about data type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   farm             4 non-null      object
 1   crop             4 non-null      object
 2   area_hectares    4 non-null      int64
 3   production_tons  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.describe()   #summary of statestics

       area_hectares  production_tons
count       4.000000         4.000000
mean       11.250000        37.500000
std         2.986079        15.779734
min         8.000000        24.000000
25%         9.500000        28.500000
50%        11.000000        33.000000
75%        12.750000        42.000000
max        15.000000        60.000000

In [ ]:
#add a new coloumn (yield
#yield=production/area
df["yield_tons_per_hectare"]=df["production_tons"]/df["area_hectares"]
print(df)

    farm   crop  area_hectares  production_tons  yield_tons_per_hectare
0  farmA  wheat             10               30                     3.0
1  farmB   rice             15               60                     4.0
2  farmC  wheat              8               24                     3.0
3  farmD  maize             12               36                     3.0

In [ ]:
print(df.iloc[[1,3]])

    farm   crop  area_hectares  production_tons  yield_tons_per_hectare
1  farmB   rice             15               60                     4.0
3  farmD  maize             12               36                     3.0

In [ ]:
print(df.loc[[1,3],["farm","crop","area_hectares"]])

    farm   crop  area_hectares
1  farmB   rice             15
3  farmD  maize             12

In [ ]:
df.iloc[[1,3],[0,1,2]]

    farm   crop  area_hectares
1  farmB   rice             15
3  farmD  maize             12

In [ ]:
#Filter data
#farms growing wheat

wheat_farms=df[df["crop"]=="wheat"]
print(wheat_farms)

    farm   crop  area_hectares  production_tons  yield_tons_per_hectare
0  farmA  wheat             10               30                     3.0
2  farmC  wheat              8               24                     3.0

In [ ]:
#farms with yield>3

high_yield=df[df["yield_tons_per_hectare"]>3]
print(high_yield)

    farm  crop  area_hectares  production_tons  yield_tons_per_hectare
1  farmB  rice             15               60                     4.0

In [ ]:
#sort farms by highest production

sorted_df=df.sort_values(by="production_tons",ascending=False)
print(sorted_df)

    farm   crop  area_hectares  production_tons  yield_tons_per_hectare
1  farmB   rice             15               60                     4.0
3  farmD  maize             12               36                     3.0
0  farmA  wheat             10               30                     3.0
2  farmC  wheat              8               24                     3.0

In [ ]:
#grouped poeration-average yield per crop
avg_yield=df.groupby("crop")["yield_tons_per_hectare"].mean()
print(avg_yield)

crop
maize    3.0
rice     4.0
wheat    3.0
Name: yield_tons_per_hectare, dtype: float64

In [ ]:
avg_yield=df.groupby("crop")["yield_tons_per_hectare"].sum()
print(avg_yield)

crop
maize    3.0
rice     4.0
wheat    6.0
Name: yield_tons_per_hectare, dtype: float64

In [1]:
import panda